### ISSUE TITLE
Add test coverage tooling.

### ISSUE THREAD

**Issue by coulix** [vuejs/vue-webpack-example#11]
It would be great to include `istanbul` with `isparta`. I have some kind of coverage but its does not show the vue.js files just yet.

**webpack.test.conf.js**

    var webpack = require('webpack');
    var config = require('./webpack.base.conf');
    var path = require('path');

    config.isparta = {
      embedSource: true,
      noAutoWrap: true,
    };

    config.module.preLoaders = [
      // transpile all files except testing sources with babel as usual
      {
          test: /\.js$/,
          exclude: [
              path.resolve('src/'),
              path.resolve('node_modules/'),
          ],
          loader: 'babel'
      },
      // transpile and instrument only testing sources with isparta.
      {
          // Adding .vue here breaks the testability of .vue components.
          //  test: /\.js||\.vue$/,
          test: /\.js$/,
          include: path.resolve('src/'),
          loader: 'isparta'
      }
    ];

    config.plugins = (config.plugins || []).concat([
      new webpack.DefinePlugin({
        'process.env': {
          NODE_ENV: '"testing"'
        }
      }),
    ]);

    module.exports = config;

**karma.conf.js**

    var webpackTestConf = require('./webpack.test.conf');
    var path = require('path');

    delete webpackTestConf.entry;

    module.exports = function(config) {
      config.set({
        //browsers: ['PhantomJS2'],
        browsers: ['Chrome'],

        frameworks: ['mocha', 'sinon-stub-promise', 'sinon', 'chai-as-promised', 'chai'],

        reporters: ['spec', 'coverage'],

        files: ['../test/unit/index.js'],

        preprocessors: {
          '../test/unit/index.js': ['webpack', 'coverage'],
        },

        webpack: webpackTestConf,

        webpackMiddleware: {
          noInfo: true
        },

        coverageReporter: {
          dir : 'coverage/',
          reporters: [
            { type: 'html', subdir: 'report-html' },
            { type: 'text-summary', subdir: '.', file: 'text-summary.txt' },
            { type: 'teamcity', subdir: '.', file: 'teamcity.txt' },
          ],
        },

        client: {
          captureConsole: true,
          mocha: {
            bail: true,
            timeout: 10000
          }
        }
      });
    };

**package.json**

    "devDependencies": {
      "express": "^4.13.3",
      "isparta-loader": "^2.0.0",
      "istanbul": "^0.4.2",
      "karma": "^0.13.15",
      "karma-chai": "^0.1.0",
      "karma-chai-as-promised": "^0.1.2",
      "karma-chrome-launcher": "^0.2.2",
      "karma-coverage": "^0.5.5",
      "karma-firefox-launcher": "^0.1.7",
      "karma-mocha": "^0.2.1",
      "karma-phantomjs-launcher": "^0.2.1",
      "karma-phantomjs2-launcher": "^0.4.0",
      "karma-sinon": "^1.0.4",
      "karma-sinon-stub-promise": "^1.0.0",
      "karma-spec-reporter": "0.0.23",
      "karma-webpack": "^1.7.0",
      "lolex": "^1.4.0",
      "mocha": "^2.4.5",
      "mocha-loader": "^0.7.1",
      "path": "^0.12.7",
      "phantomjs": "^1.9.19",
      "sinon": "^1.17.3",
      "sinon-chai": "^2.8.0",
      "sinon-stub-promise": "^1.1.0"
    }

![image](https://cloud.githubusercontent.com/assets/26057/14094367/3885adf6-f51b-11e5-8458-d5d1745f7d55.png)

**Comment by yyx990803** [comment]
Check out the config in the vue-cli webpack template.
